export const products = [
    {
      id: 1,
      name: "Premium Wireless Headphones",
      price: 299.99,
      originalPrice: 399.99,
      rating: 4.8,
      reviews: 124,
      image: "/premium-wireless-headphones.png",
      category: "Electronics",
    },
    {
      id: 2,
      name: "Smart Fitness Watch",
      price: 199.99,
      originalPrice: 249.99,
      rating: 4.6,
      reviews: 89,
      image: "/smart-fitness-watch.png",
      category: "Sports & Fitness",
    },
    {
      id: 3,
      name: "Minimalist Backpack",
      price: 79.99,
      originalPrice: 99.99,
      rating: 4.9,
      reviews: 156,
      image: "/minimalist-backpack.png",
      category: "Fashion",
    },
    {
      id: 4,
      name: "Bluetooth Speaker",
      price: 149.99,
      originalPrice: 179.99,
      rating: 4.7,
      reviews: 203,
      image: "/bluetooth-speaker.png",
      category: "Electronics",
    },
    {
      id: 5,
      name: "Ergonomic Office Chair",
      price: 449.99,
      originalPrice: 599.99,
      rating: 4.5,
      reviews: 67,
      image: "/ergonomic-office-chair.png",
      category: "Home & Garden",
    },
  ];

  export const categories = [
    { name: "All" },
    { name: "Electronics" },
    { name: "Fashion" },
    { name: "Home & Garden" },
    { name: "Sports & Fitness" },
];